version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '2'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '2'

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiYmVhMGJlODhjOWNmY2RiYzQ3NjE1NWNhNTgxN2MwNzgiLCJ0IjoiM2ZhMTgzMjAtY2QzMS00YmU5LTgxMzMtMzAyYjZmZmRlMGYwIiwicyI6Ik4yUmtOekE0TWpFdE1EazRZUzAwWm1RekxUbGpZMlF0WldVNVpEVmpaR1UwTWpJNSJ9
    
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

networks:
  mynetwork:
    driver: bridge
